-- Create settings table for storing app configuration
CREATE TABLE IF NOT EXISTS public.settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_time text NOT NULL DEFAULT '08:00 AM',
  ai_model text NOT NULL DEFAULT 'openai/gpt-oss-20b:free',
  ai_system_prompt text NOT NULL DEFAULT '',
  max_pages_per_source integer NOT NULL DEFAULT 5,
  max_jobs_per_keyword integer NOT NULL DEFAULT 50,
  delay_between_requests integer NOT NULL DEFAULT 2,
  retry_count integer NOT NULL DEFAULT 3,
  timeout integer NOT NULL DEFAULT 30,
  concurrency integer NOT NULL DEFAULT 2,
  ai_request_budget_daily integer NOT NULL DEFAULT 100,
  search_provider text NOT NULL DEFAULT 'duckduckgo',
  enabled_sources jsonb NOT NULL DEFAULT '["linkedin","greenhouse","lever","ashby"]',
  updated_at timestamp with time zone DEFAULT now()
);

-- Insert default settings row if table was just created
INSERT INTO public.settings (id, ai_system_prompt)
VALUES (1, 'You are an expert technical recruiting assistant.\n\nYour task is to evaluate whether a job posting matches the user search keyword and should be kept.\n\nEvaluation rules:\n1. The job title should closely match the search keyword or be a reasonable variation.\n2. The required skills technologies or responsibilities should be relevant to the keyword.\n3. Ignore the location work arrangement (remote hybrid onsite) salary and years of experience unless they clearly make the job unrelated.\n4. Accept jobs even if they are not a perfect match. Favor keeping potentially relevant jobs rather than rejecting them.\n5. Reject only jobs that are clearly unrelated to the search keyword.\n6. If there is insufficient information prefer accepted rather than rejecting.')
ON CONFLICT (id) DO NOTHING;

-- Create scraper_runs table for tracking health/status
CREATE TABLE IF NOT EXISTS public.scraper_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status text NOT NULL DEFAULT 'idle',
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  jobs_found integer DEFAULT 0,
  jobs_saved integer DEFAULT 0,
  error_message text,
  captcha_blocked_sources jsonb DEFAULT '[]',
  created_at timestamp with time zone DEFAULT now()
);

-- Enable Row Level Security (optional but recommended)
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scraper_runs ENABLE ROW LEVEL SECURITY;

-- Allow public read access (since the frontend uses anon key)
CREATE POLICY "Allow public read" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON public.scraper_runs FOR SELECT USING (true);
CREATE POLICY "Allow public update" ON public.settings FOR UPDATE USING (true);
CREATE POLICY "Allow public insert" ON public.scraper_runs FOR INSERT WITH CHECK (true);

-- Allow the anon role to insert and update
GRANT ALL ON public.settings TO anon, authenticated, service_role;
GRANT ALL ON public.scraper_runs TO anon, authenticated, service_role;
GRANT USAGE ON SEQUENCE public.settings_id_seq TO anon, authenticated, service_role;
GRANT USAGE ON SEQUENCE public.scraper_runs_id_seq TO anon, authenticated, service_role;
